"""
agents.state
------------
Shared experiment state schema for every agentic RAG pattern. Defines
the ``ExperimentState`` typed dict consumed by all graphs, an initial
state factory that pre-populates every field tools may read, and a
deduplication helper that picks the highest-scoring chunk for each
(source_file, header_2, header_3) tuple.
"""

from __future__ import annotations

from typing import TypedDict


class _RequiredFields(TypedDict):
    question: str
    pattern_name: str


class ExperimentState(_RequiredFields, total=False):
    """Shared state schema for all graph patterns.

    Attributes:
        question (str): The user's input question (required).
        pattern_name (str): Identifier of the graph pattern being executed (required).
        company (str | None): Insurance company extracted from the question.
        product (str | None): Insurance product extracted from the question.
        intent (str | None): Classified question intent (e.g. "faq", "coverage").
        entities (list[str]): Named entities extracted from the question.
        is_multi_part (bool): Whether the question contains multiple sub-questions.
        language (str): ISO 639-1 language code detected in the question.
        rewritten_queries (list[str]): Query variants generated by the rewriter.
        retrieved_chunks (list[dict]): Chunks returned by the retriever or reranker.
        evidence_chunks (list[dict]): Compact evidence subset selected for synthesis.
        selected_prompt_template (str | None): Key of the chosen prompt template.
        system_prompt (str | None): Full system prompt text for the answer model.
        citations (list[dict]): Structured citation objects with inline references.
        answer_body (str | None): Normalised answer text without the references footer.
        answer_with_references (str | None): Full answer including the references footer.
        answer (str | None): Final answer returned to the caller.
        error (str | None): Error message set when a node fails.
        metadata (dict): Accumulated process and usage metrics for the run.
    """

    company: str | None
    product: str | None
    intent: str | None
    entities: list[str]
    is_multi_part: bool
    language: str
    rewritten_queries: list[str]
    retrieved_chunks: list[dict]
    evidence_chunks: list[dict]
    selected_prompt_template: str | None
    system_prompt: str | None
    citations: list[dict]
    answer_body: str | None
    answer_with_references: str | None
    answer: str | None
    error: str | None
    metadata: dict


def make_initial_state(
    question: str,
    pattern_name: str,
    *,
    company: str | None = None,
    product: str | None = None,
) -> dict:
    """Create a fresh initial state with all fields pre-populated.

    Args:
        question (str): The user's input question.
        pattern_name (str): Identifier of the graph pattern to execute.
        company (str | None): Pre-known insurance company name, or None to let the
            parser detect it.
        product (str | None): Pre-known insurance product name, or None to let the
            parser detect it.

    Returns:
        dict: A fully initialised state dictionary compatible with ExperimentState.
    """
    return {
        "question": question,
        "company": company,
        "product": product,
        "intent": None,
        "entities": [],
        "is_multi_part": False,
        "language": "pl",
        "rewritten_queries": [],
        "retrieved_chunks": [],
        "evidence_chunks": [],
        "selected_prompt_template": None,
        "system_prompt": None,
        "citations": [],
        "answer_body": None,
        "answer_with_references": None,
        "answer": None,
        "error": None,
        "pattern_name": pattern_name,
        "metadata": {},
    }


def deduplicate_chunks(chunks: list[dict]) -> list[dict]:
    """Deduplicate chunks and keep the highest-scoring copy for each position.

    Args:
        chunks (list[dict]): Retrieved chunks, each with optional ``source_file``,
            ``metadata.header_2``, ``metadata.header_3``, and ``score`` fields.

    Returns:
        list[dict]: Deduplicated chunks sorted by descending score.
    """
    seen: dict[tuple, dict] = {}
    for chunk in chunks:
        meta = chunk.get("metadata", {})
        # Key on (file, header_2, header_3): header_1 is the document title and
        # too coarse; header_2 + header_3 identifies a specific sub-clause.
        # Multiple chunks from the same clause keep only the highest-scored copy.
        key = (
            chunk.get("source_file", ""),
            meta.get("header_2", ""),
            meta.get("header_3", ""),
        )
        existing = seen.get(key)
        if existing is None or chunk.get("score", 0) > existing.get("score", 0):
            seen[key] = chunk
    return sorted(seen.values(), key=lambda c: c.get("score", 0), reverse=True)
